import type { Category, SubCategoryRecord } from '@/types/api'

export const mockCategories: Category[] = [
  {
    id: 'cat-001',
    name_en: 'Electronics',
    name_ar: 'إلكترونيات',
    image_url: 'https://cdn.bidmart.com/cats/electronics.png',
    icon_url: 'https://cdn.bidmart.com/cats/electronics-icon.png',
    display_order: 1,
    is_active: true,
    subCategoriesCount: 2,
    created_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-002',
    name_en: 'Fashion',
    name_ar: 'أزياء',
    image_url: 'https://cdn.bidmart.com/cats/fashion.png',
    icon_url: 'https://cdn.bidmart.com/cats/fashion-icon.png',
    display_order: 2,
    is_active: true,
    subCategoriesCount: 0,
    created_at: '2024-01-05T00:00:00.000Z',
  },
  {
    id: 'cat-003',
    name_en: 'Home & Garden',
    name_ar: 'المنزل والحديقة',
    image_url: 'https://cdn.bidmart.com/cats/home.png',
    icon_url: 'https://cdn.bidmart.com/cats/home-icon.png',
    display_order: 3,
    is_active: true,
    subCategoriesCount: 1,
    created_at: '2024-01-10T00:00:00.000Z',
  },
  {
    id: 'cat-004',
    name_en: 'Sports & Outdoors',
    name_ar: 'الرياضة والأنشطة الخارجية',
    image_url: 'https://cdn.bidmart.com/cats/sports.png',
    icon_url: 'https://cdn.bidmart.com/cats/sports-icon.png',
    display_order: 4,
    is_active: true,
    subCategoriesCount: 0,
    created_at: '2024-02-01T00:00:00.000Z',
  },
  {
    id: 'cat-005',
    name_en: 'Automotive',
    name_ar: 'السيارات',
    image_url: 'https://cdn.bidmart.com/cats/automotive.png',
    icon_url: 'https://cdn.bidmart.com/cats/automotive-icon.png',
    display_order: 5,
    is_active: false,
    subCategoriesCount: 0,
    created_at: '2024-03-01T00:00:00.000Z',
  },
  {
    id: 'cat-006',
    name_en: 'Collectibles',
    name_ar: 'مقتنيات',
    image_url: 'https://cdn.bidmart.com/cats/collectibles.png',
    icon_url: 'https://cdn.bidmart.com/cats/collectibles-icon.png',
    display_order: 6,
    is_active: true,
    subCategoriesCount: 0,
    created_at: '2024-04-01T00:00:00.000Z',
  },
]

export const mockSubCategories: SubCategoryRecord[] = [
  // Electronics subs
  {
    id: 'sub-001',
    category_id: 'cat-001',
    name_en: 'Phones & Tablets',
    name_ar: 'هواتف وتابلت',
    image_url: null,
    display_order: 1,
    is_active: true,
    created_at: '2024-01-02T00:00:00.000Z',
    updated_at: '2024-01-02T00:00:00.000Z',
    description_en: null,
    description_ar: null,
  },
  {
    id: 'sub-002',
    category_id: 'cat-001',
    name_en: 'Laptops',
    name_ar: 'أجهزة محمولة',
    image_url: null,
    display_order: 2,
    is_active: true,
    created_at: '2024-01-02T00:00:00.000Z',
    updated_at: '2024-01-02T00:00:00.000Z',
    description_en: null,
    description_ar: null,
  },
  {
    id: 'sub-003',
    category_id: 'cat-001',
    name_en: 'Gaming Consoles',
    name_ar: 'أجهزة ألعاب',
    image_url: null,
    display_order: 3,
    is_active: true,
    created_at: '2024-01-02T00:00:00.000Z',
    updated_at: '2024-01-02T00:00:00.000Z',
    description_en: null,
    description_ar: null,
  },
  {
    id: 'sub-004',
    category_id: 'cat-001',
    name_en: 'Accessories',
    name_ar: 'إكسسوارات',
    image_url: null,
    display_order: 4,
    is_active: false,
    created_at: '2024-01-02T00:00:00.000Z',
    updated_at: '2024-01-02T00:00:00.000Z',
    description_en: null,
    description_ar: null,
  },
  // Fashion subs
  {
    id: 'sub-005',
    category_id: 'cat-002',
    name_en: "Men's Clothing",
    name_ar: 'ملابس رجالية',
    image_url: null,
    display_order: 1,
    is_active: true,
    created_at: '2024-01-06T00:00:00.000Z',
    updated_at: '2024-01-06T00:00:00.000Z',
    description_en: null,
    description_ar: null,
  },
  {
    id: 'sub-006',
    category_id: 'cat-002',
    name_en: "Women's Clothing",
    name_ar: 'ملابس نسائية',
    image_url: null,
    display_order: 2,
    is_active: true,
    created_at: '2024-01-06T00:00:00.000Z',
    updated_at: '2024-01-06T00:00:00.000Z',
    description_en: null,
    description_ar: null,
  },
  {
    id: 'sub-007',
    category_id: 'cat-002',
    name_en: 'Shoes',
    name_ar: 'أحذية',
    image_url: null,
    display_order: 3,
    is_active: true,
    created_at: '2024-01-06T00:00:00.000Z',
    updated_at: '2024-01-06T00:00:00.000Z',
    description_en: null,
    description_ar: null,
  },
  // Home & Garden subs
  {
    id: 'sub-008',
    category_id: 'cat-003',
    name_en: 'Furniture',
    name_ar: 'أثاث',
    image_url: null,
    display_order: 1,
    is_active: true,
    created_at: '2024-01-11T00:00:00.000Z',
    updated_at: '2024-01-11T00:00:00.000Z',
    description_en: null,
    description_ar: null,
  },
  {
    id: 'sub-009',
    category_id: 'cat-003',
    name_en: 'Kitchen',
    name_ar: 'مطبخ',
    image_url: null,
    display_order: 2,
    is_active: true,
    created_at: '2024-01-11T00:00:00.000Z',
    updated_at: '2024-01-11T00:00:00.000Z',
    description_en: null,
    description_ar: null,
  },
  // Sports subs
  {
    id: 'sub-010',
    category_id: 'cat-004',
    name_en: 'Gym Equipment',
    name_ar: 'أجهزة رياضية',
    image_url: null,
    display_order: 1,
    is_active: true,
    created_at: '2024-02-02T00:00:00.000Z',
    updated_at: '2024-02-02T00:00:00.000Z',
    description_en: null,
    description_ar: null,
  },
]

export function getMockSubCategories(categoryId: string): SubCategoryRecord[] {
  return mockSubCategories.filter((s) => s.category_id === categoryId)
}
